#!/bin/bash

PATH_TEST=service/tests/
RUN_TEST="-m unittest discover"
path=$PWD

vacio=`locate $PWD/*/tests | grep $1$`
echo "$PWD/*/tests"
echo $vacio

encontro=false
for path in  `locate $PWD/*/tests | grep $1$`;
do
	encontro=true
	python $RUN_TEST  $path 
	echo "ejecutando--> python" $RUN_TEST $path
done

if test !$encontro;
then
	variable=${PWD%*/service/*}
	variable2=${PWD%*/service}
	if test "$variable" = "$PWD" -a "$variable2" = "$PWD";
	then 
		echo "no se encontro el directorio"
	else
		if test $variable = $PWD; 	
		then	
			for path in  `locate $variable2/*/tests | grep $1$`;
			do
				encontro=true
				python $RUN_TEST  $path 
				echo "ejecutando--> python" $RUN_TEST $path
			done

			
		else
			for path in  `locate $variable/*/tests | grep $1$`;
			do
				encontro=true
				python $RUN_TEST  $path 
				echo "ejecutando--> python" $RUN_TEST $path
			done
		fi
	fi
fi
	
